import Head from "next/head";
import styles from "./Noticias.module.css"

// Components
import NavbarComponent from "../../components/Navbar";
import CardMuiComponent from "../../components/CardMUI";
import Footer from "../../components/Footer";

let navbar = [
    {"name":"Página Principal","href":"/","number":"1"},
    {"name":"Instagram","href":"https://www.instagram.com/aruanda.capoeira/","number":"2"},
    {"name":"Locais de Treino","href":"/locais-treino","number":"3"},
]

let cardsMui = [
    {"title": "Titulo 1", "text": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","image": "https://escutaqueebom.com/wp-content/uploads/2018/08/Sidoka.jpg", "alt":"Sidoka", "height":"390"},
    {"title": "Titulo 2", "text": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","image": "https://escutaqueebom.com/wp-content/uploads/2018/08/Sidoka.jpg", "alt":"Sidoka", "height":"390"},
    {"title": "Titulo 3", "text": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","image": "https://escutaqueebom.com/wp-content/uploads/2018/08/Sidoka.jpg", "alt":"Sidoka", "height":"390"},
]

export default function Noticias(){
    return(
        <>
            <Head>
                <title>Aruanda Capoeira - DF</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavbarComponent
                link={navbar}
                image="/labslogo.svg"
            />
            <h1 className={styles.text}>
                Eventos Aruanda capoeira
            </h1>

            <div className={styles.alinhamento_iframe}>
                <CardMuiComponent
                    link={cardsMui}
                    color="gray"
                    width="750"
                />
            </div>
            <Footer/>
        </>
    )
}