import Head from "next/head";
// import styles from "../../styles/Home.module.css"
import styles from "./Locais.module.css"

// Components
import NavbarComponent from "../../components/Navbar";
import Footer from "../../components/Footer";

let navbar = [
    {
        "name":"Página Principal",
        "href":"/",
        "number":"1"
    },
    {
        "name":"Eventos",
        "href":"/eventos",
        "number":"2"
    },
    {
        "name":"Historia Aruanda",
        "href":"/historia-aruanda",
        "number":"3"
    },
]

export default function LocaisTreino(){
    return(
        <div className={styles.image_background}>
            <Head>
                <title>Aruanda Capoeira - DF</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <NavbarComponent link={navbar} image="/logo.svg"/>
            <div style={{paddingTop:"120px"}}>
                <h1 className={styles.text}>
                    Locais de Treino Aruanda Capoeira
                </h1>

                <div className={styles.alinhamento_iframe}>
                    <iframe
                        src="https://www.google.com/maps/d/u/0/embed?mid=18YDTaHsM4rA564kHBtnJXJKGwYzxypI&ehbc=2E312F"
                        className={styles.iframe}
                    >
                    </iframe>
                </div>
            </div>
            <Footer/>
        </div>
    )
}