import * as React from 'react';
import styles from "./Emendas.module.css"
import Head from "next/head";

// Components
import NavbarComponent from "../../components/Navbar";
import CardLateral from "../../components/CardLateral";

let navbar = [
    {
        "name":"Página Principal",
        "href":"/",
        "number":"1"
    },
    {
        "name":"Eventos",
        "href":"/eventos",
        "number":"2"
    },
    {
        "name":"Transparência das emendas",
        "href":"/emendas",
        "number":"3"
    },
]

let cardLateral = [
    {
        "title":"Papo de Capoeira III",
        "date":"01 e 02 de novembro (2024)",
        "text":"Emenda Parlamentar",
        "href":"/PlanilhaCustosPapoCapoeira3.xlsx",
        "color":"",
        "image":"PapoDeCapoeira3.jpeg"
    },
    
]

export default function EmandasParlamentares() {
    return (
    <>
        
        <Head>
            <title>Aruanda Capoeira - DF</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.svg" />
        </Head>

        <NavbarComponent link={navbar} image="/logo.svg"/>

        <div className={styles.image_background}>
            <h2 className={styles.title_historia}>
                Recursos de emendas de 2024 recebidos pelo MIR
            </h2>
            <p className={styles.text_link}>
                Para mais informações,{" "}
                <a 
                    href="https://clusterqap2.economia.gov.br/extensions/painel-transferencias-discricionarias-e-legais/painel-transferencias-discricionarias-e-legais.html" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className={styles.link}
                >
                    acesse o link
                </a>.
            </p>
            <div className={styles.espacamento}>
                <CardLateral link={cardLateral} />
            </div>

        </div>
    </>

       
    );
}