import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavbarComponent from "../components/Navbar";
import CarouselComponent from "../components/Caroussel";
import CardComponent from "../components/Cards";

let cards = [
    { "name": "Pedro Henrique Martins Teixeira", "job": "Analista de requisistos", "information": "Um processo sensacional, todo carinho que a G4F deu desde o inicío do projeto, além da liberdade para que todos os selecionados pudessem apresentar suas qualidades durante o  processo seletivo, tudo foi muito muito bem planejado e excecutado. Quero retribuir toda expectativa que a G4F depositou nos novos profissionais do projeto Trainee da melhor forma. ", "src": "/Ellipse1.png"},
    { "name": "Eduardo borges", "job": "Analista de requisitos", "information": "Participei do processo seletivo do programa trainee da G4F, no qual a dinâmica me surpreendeu. Foi uma experiência muito boa por juntar 5 pessoas que nunca se viram na vida para desenvolver  a solução de um problema específico em 3 dias. Meu grupo da dinâmica deu muito certo, e conseguimos entregar nossa ideia. Hoje posso me desenvolver dentro de um ambiente real e tenho maior oportunidade de crescimento profissional  graças ao projeto.",  "src": "/Ellipse2.png"},
]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NavbarComponent/>


        <div className={styles.caroussel}>
            <h2 style={{textAlign:"center"}}>Aruanda Capoeira</h2>
            <CarouselComponent/>
        </div>

        <h2 style={{textAlign:"center"}}>Conheça a nossa história :</h2>

        <div className={styles.luca}>
            <p>Lorem Ipsum é simplesmente um texto fictício da indústria tipográfica e de impressão. Lorem Ipsum tem sido o texto fictício padrão da indústria desde os anos 1500, quando um impressor desconhecido pegou uma cozinha de tipos e embaralhou-a para fazer um livro de espécimes de tipos. Ele sobreviveu não apenas cinco séculos, mas também o salto para a composição eletrônica, permanecendo essencialmente inalterado. Foi popularizado na década de 1960 com o lançamento de folhas Letraset contendo passagens de Lorem Ipsum e, mais recentemente, com software de editoração eletrônica como Aldus PageMaker, incluindo versões de Lorem Ipsum.</p>
        </div>

        <h2 style={{textAlign:"center"}}>Mestres da casa:</h2>


        <div className={styles.alinhamento_cards_candidatos}>
            {cards.map((item,index) => {
                return (
                    <div key={index} style={{padding:"10px"}}>
                        <CardComponent
                            information={item.information}
                            name={item.name}
                            job={item.job}
                            backgroundColor={item.backgroundColor}
                            src={item.src}
                        />
                    </div>
                )
            })}
        </div>

        <h3 style={{textAlign:"center"}}>Entre em contato:</h3>

        <footer className={styles.footer}>
        <a
          // href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
         Aruanda Capoeira Brasília
          <span className={styles.logo}>
            {/*<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />*/}
          </span>
        </a>
      </footer>
    </div>
  )
}
