import Head from 'next/head'
import styles from '../styles/Home.module.css'

// Components
import Footer from "../components/Footer";

// Subpages
import Topo from "../subpages/Topo";
import PorquePraticar from "../subpages/PorquePraticar";
import Horarios from "../subpages/Horarios";
import Mestres from "../subpages/Mestres";
import Beneficios from "../subpages/Beneficios";

export default function Home() {
  return (
    <div className={styles.image_background}>
      <Head>
        <title>Aruanda Capoeira - DF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

        <Topo/>
        <PorquePraticar/>
        <Horarios/>
        <Beneficios/>
        <Mestres/>

        <Footer/>
    </div>
  )
}
