import Head from 'next/head'
import Image from 'next/image'
// import Link from 'next/link'
import styles from '../styles/Home.module.css'
import {Link} from "@mui/material";

// Components
import NavbarComponent from "../components/Navbar";
import CarouselComponent from "../components/Caroussel";
import CardComponent from "../components/Cards";
import Footer from "../components/Footer";

// Subpages
import Historia from "../subpages/Historia";
import ImageAvatars from "../components/Avatar";
import Icons from "../subpages/Icons";
// import Topo from "../subpages/Topo";

let cards = [
    { "name": "Mestra Michellinha", "job": "Brasília - DF", "information": "Um processo sensacional, todo carinho que a G4F deu desde o inicío do projeto, além da liberdade para que todos os selecionados pudessem apresentar suas qualidades durante o  processo seletivo, tudo foi muito muito bem planejado e excecutado. Quero retribuir toda expectativa que a G4F depositou nos novos profissionais do projeto Trainee da melhor forma. ", "src": "/Michellinha.png", "width":"420"},
    { "name": "Mestre Igor", "job": "Brasília - DF", "information": "Participei do processo seletivo do programa trainee da G4F, no qual a dinâmica me surpreendeu. Foi uma experiência muito boa por juntar 5 pessoas que nunca se viram na vida para desenvolver  a solução de um problema específico em 3 dias. Meu grupo da dinâmica deu muito certo, e conseguimos entregar nossa ideia. Hoje posso me desenvolver dentro de um ambiente real e tenho maior oportunidade de crescimento profissional  graças ao projeto.",  "src": "/igor.png", "width":"420"},
    { "name": "Mestre Paulo Renato", "job": "Brasília - DF", "information": "Participei do processo seletivo do programa trainee da G4F, no qual a dinâmica me surpreendeu. Foi uma experiência muito boa por juntar 5 pessoas que nunca se viram na vida para desenvolver  a solução de um problema específico em 3 dias. Meu grupo da dinâmica deu muito certo, e conseguimos entregar nossa ideia. Hoje posso me desenvolver dentro de um ambiente real e tenho maior oportunidade de crescimento profissional  graças ao projeto.",  "src": "/paulo.png", "width":"420"},
    { "name": "Mestre Paulo Renato", "job": "Brasília - DF", "information": "Participei do processo seletivo do programa trainee da G4F, no qual a dinâmica me surpreendeu. Foi uma experiência muito boa por juntar 5 pessoas que nunca se viram na vida para desenvolver  a solução de um problema específico em 3 dias. Meu grupo da dinâmica deu muito certo, e conseguimos entregar nossa ideia. Hoje posso me desenvolver dentro de um ambiente real e tenho maior oportunidade de crescimento profissional  graças ao projeto.",  "src": "/paulo.png", "width":"420"},
]

let carroussel = [
    { "title":"Encontro de Bambas 2017", "text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit.", "src":"EDB2017(2).jpg"},
    { "title":"Encontro de Bambas 2019", "text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit.", "src":"EDB2019.jpg"},
    { "title":"Encontro de Bambas 2020", "text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit.", "src":"EDB.webp"},
]

let navbar = [
    {"name":"Notícias","href":"/noticias","number":"1"},
    {"name":"Locais de Treino","href":"/locais-treino","number":"2"},
    {"name":"Conheça a nossa história","href":"#jornada","number":"3"},
    {"name":"Mestres da casa","href":"#mestres","number":"4"},
]

export default function Home() {
  return (
    <div>
      <Head>
        <title>Aruanda Capoeira - DF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <NavbarComponent link={navbar} image="/labslogo.svg"/>

        {/*<Topo/>*/}

        {/*<div className={styles.caroussel}>*/}
        <div style={{paddingTop:"95px"}}>
            <CarouselComponent link={carroussel}/>
        </div>
        {/*</div>*/}

        <div className={styles.text_historia} id="jornada">
            <h2> Conheça a nossa história</h2>
            <Historia/>
        </div>


        <h2 className={styles.text_mestres} id="mestres">
            Mestres da casa
        </h2>

        <div className={styles.alinhamento_cards_candidatos}>
            {cards.map((item,index) => {
                return (
                    <div key={index} style={{padding:"10px"}}>
                        <CardComponent
                            information={item.information}
                            name={item.name}
                            job={item.job}
                            backgroundColor={item.backgroundColor}
                            src={item.src}
                            width={item.width}
                        />
                    </div>
                )
            })}
        </div>

        <Icons/>
        <Footer/>
    </div>
  )
}
