import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Button} from "react-bootstrap";

// Components
import Footer from "../components/Footer";

// Subpages
import Horarios from "../subpages/Horarios";
import Mestres from "../subpages/Mestres";
import Beneficios from "../subpages/Beneficios";
import Topo from "../subpages/Topo";
import PorquePraticar from "../subpages/PorquePraticar";

let cardsProcessoSeletivo = [
    {
        "title":"Atende a todos os públicos e faixas etárias",
        "number":"1",
        "text":" Nos dias atuais, existem inúmeros profissionais especialistas em áreas específicas para o treinamento de capoeira: capoeira para crianças, capoeira para atletas, capoeira para a terceira idade, dentre outros.",
        "image":"/retangulo3.svg"
    },
    {
        "title":"Ajuda a liberar o estresse",
        "number":"2",
        "text":" A capoeira serve de válvula de escape; é uma forma de liberar o estresse de uma forma lúdica e saudável." ,
        "image":"/retangulo3.svg"
    },
]



let cards = [
    {
        "title": "Titulo 1",
        "text": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        "image": "https://escutaqueebom.com/wp-content/uploads/2018/08/Sidoka.jpg",
        "alt":"Sidoka",
        "height":"290"
    },
]

export default function Home() {
  return (
    <div className={styles.image_background}>
      <Head>
        <title>Aruanda Capoeira - DF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Topo/>
        <PorquePraticar/>
        <Horarios/>
        {/*<Beneficios/>*/}
        <Mestres/>

        <div className={styles.button}>
            <Button variant="danger" href="/historia-aruanda">
                Conheça mais sobre a nossa historia
            </Button>
        </div>

        <Footer/>
    </div>
  )
}
