import Head from "next/head";
import styles from "./Evento.module.css"

// Components
import NavbarComponent from "../../components/Navbar";
import CardLateral from "../../components/CardLateral";
import CardBootstrap from "../../components/CardBootstrap";
import Footer from "../../components/Footer";

let navbar = [
    {
        "name":"Página Principal",
        "href":"/",
        "number":"1"
    },
    {
        "name":"Historia Aruanda",
        "href":"/historia-aruanda",
        "number":"2"
    },
]

let cardLateral = [
    // {
    //     "title":"Encontro de Bambas 2018",
    //     "date":"13 de janeiro a 15 de janeiro",
    //     "text":"Valor do ingresso: R$ 50,00",
    //     "href":"/",
    //     "color":"",
    //     "image":"EDB2017.jpeg"
    // },
    //
    // {
    //     "title":"Encontro de Bambas 2020",
    //     "date":"13 de janeiro a 15 de janeiro",
    //     "text":"Valor do ingresso: R$ 50,00",
    //     "href":"/",
    //     "color":"",
    //     "image":"Michellinha.png"
    // },
    // {
    //     "title":"Encontro de Bambas 2020",
    //     "date":"13 de janeiro a 15 de janeiro",
    //     "text":"Valor do ingresso: R$ 50,00",
    //     "href":"/",
    //     "color":"",
    //     "image":"test.jpeg"
    // },
    {
        "title":"Encontro de Bambas 2020",
        "date":"13 de janeiro a 15 de janeiro",
        "text":"Valor do ingresso: R$ 50,00",
        "href":"/",
        "color":"",
        "image":"1.jpg"
    },
    {
        "title":"Encontro de Bambas 2020",
        "date":"13 de janeiro a 15 de janeiro",
        "text":"Valor do ingresso: R$ 50,00",
        "href":"/",
        "color":"",
        "image":"2.jpg"
    },
    {
        "title":"Encontro de Bambas 2020",
        "date":"13 de janeiro a 15 de janeiro",
        "text":"Valor do ingresso: R$ 50,00",
        "href":"/",
        "color":"",
        "image":"3.jpg"
    },
    {
        "title":"Encontro de Bambas 2020",
        "date":"13 de janeiro a 15 de janeiro",
        "text":"Valor do ingresso: R$ 50,00",
        "href":"/",
        "color":"",
        "image":"4.jpg"
    },
]

let cardBootstrap = [
    {
        "title":"Encontro de Bambas 2022",
        "date":"15 de março a 17 de março",
        "hour":"Valor do ingresso: R$ 50,00",
        "src":"/EDB2017.jpeg",
        // "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    },
    {
        "title":"Encontro de Bambas 2022",
        "date":"15 de março a 17 de março",
        "hour":"Valor do ingresso: R$ 50,00",
        "src":"/EDB2017(2).jpg",
        // "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    },
    {
        "title":"Encontro de Bambas 2022",
        "date":"15 de março a 17 de março",
        "hour":"Valor do ingresso: R$ 50,00",
        "src":"/test.jpeg",
        // "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    },
    {
        "title":"Encontro de Bambas 2022",
        "date":"15 de março a 17 de março",
        "hour":"Valor do ingresso: R$ 50,00",
        "src":"/EDB.webp",
        // "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    },
    {
        "title":"Encontro de Bambas 2022",
        "date":"15 de março a 17 de março",
        "hour":"Valor do ingresso: R$ 50,00",
        "src":"/EDB.webp",
        // "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    },
    {
        "title":"Encontro de Bambas 2022",
        "date":"15 de março a 17 de março",
        "hour":"Valor do ingresso: R$ 50,00",
        "src":"/EDB.webp",
        // "description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    },
]


export default function Eventos(){
    return(
        <div className={styles.image_background}>
            <Head>
                <title>Aruanda Capoeira - DF</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <NavbarComponent link={navbar} image="/logo.svg"/>
            <div className={styles.espacamento}>
                <h1 className={styles.text}>
                    Eventos Aruanda capoeira
                </h1>

                {/*<div className={styles.espacamento_cardBootstrap}>*/}
                {/*    <CardBootstrap link={cardBootstrap}/>*/}
                {/*</div>*/}

                <div className={styles.alinhamento_cards}>
                    <CardLateral link={cardLateral} />
                </div>
            </div>
            <Footer/>

        </div>
    )
}