import Head from "next/head";
import styles from "./Evento.module.css"

// Components
import NavbarComponent from "../../components/Navbar";
import Footer from "../../components/Footer";
import CardLateral from "../../components/CardLateral";

let navbar = [
    {
        "name":"Página Principal",
        "href":"/",
        "number":"1"
    },
    {
        "name":"Historia Aruanda",
        "href":"/historia-aruanda",
        "number":"2"
    },
    {
        "name":"Locais de Treino",
        "href":"/locais-treino",
        "number":"2"
    },
]

let cardLateral = [
    {
        "title":"Encontro de Bambas 2018",
        "date":"13 de janeiro a 15 de janeiro",
        "text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "href":"/",
        "color":"",
        "image":"EDB2017.jpeg"
    },

    {
        "title":"Encontro de Bambas 2020",
        "date":"13 de janeiro a 15 de janeiro",
        "text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "href":"/",
        "color":"",
        "image":"Michellinha.png"
    },
    // {
    //     "title":"Encontro de Bambas 2020",
    //     "date":"13 de janeiro a 15 de janeiro",
    //     "text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    //     "href":"/",
    //     "color":"",
    //     "image":"EDB2017(2).jpg"
    // },
]

export default function Eventos(){
    return(
        <div className={styles.image_background}>
            <Head>
                <title>Aruanda Capoeira - DF</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <NavbarComponent link={navbar} image="/logo.svg"/>
            <div className={styles.espacamento}>
                <h1 className={styles.text}>
                    Eventos Aruanda capoeira
                </h1>

                <div className={styles.alinhamento_cards}>
                    <CardLateral link={cardLateral} />
                </div>
            </div>

            <Footer/>
        </div>
    )
}