import Head from "next/head";
import styles from "./Evento.module.css"

// Components
import NavbarComponent from "../../components/Navbar";
import CardLateral from "../../components/CardLateral";
import Footer from "../../components/Footer";

let navbar = [
    {
        "name":"Página Principal",
        "href":"/",
        "number":"1"
    },
    {
        "name":"Historia Aruanda",
        "href":"/historia-aruanda",
        "number":"2"
    },
]

let cardLateral = [
    {
        "title":"Papo de Capoeira I",
        "date":"10 a 12 de Dezembro (2021)",
        "text":"Emenda Parlamentar",
        "href":"/PlanilhaCustos.pdf",
        "color":"",
        "image":"PapoDeCapoeira1.jpeg"
    },
    {
        "title":"Encontro de Bambas",
        "date":"08 a 10 de Julho (2022)",
        "text":"Valor do ingresso: R$ 50,00",
        "href":"",
        "color":"",
        "image":"4.jpg"
    },
    {
        "title":"Papo de Capoeira III",
        "date":"10 a 12 de Dezembro (2024)",
        "text":"Valor do ingresso: R$ 60,00",
        "href":"",
        "color":"",
        "image":"PapoDeCapoeira3.jpeg"
    },
    
]

export default function Eventos(){
    return(
        <div className={styles.image_background}>
            <Head>
                <title>Aruanda Capoeira - DF</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <NavbarComponent link={navbar} image="/logo.svg"/>
            <div className={styles.espacamento}>
                <h1 className={styles.text}>
                    Eventos Aruanda capoeira
                </h1>

                <div className={styles.alinhamento_cards}>
                    <CardLateral link={cardLateral} />
                </div>
            </div>
            <Footer/>

        </div>
    )
}